[project]
name = "riyadh-ksu-geoproject"
version = "0.1.0"
description = "Riyadh KSU Spatial Analysis"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.1.1",
    "marimo>=0.18.4",
    "psycopg2-binary",
]